- name: Update yum
  yum:
    update_cache: yes
  become: yes

- name: Install Requirements for building Qulacs via yum
  yum:
    name:
      - boost-devel
      - cmake
      - gcc
      - gcc-c++
      - make
      - python38-devel
  become: yes

