- name: Update apt
  apt:
    update_cache: yes
    upgrade: "yes"
  become: yes

- name: Install dependencies for qulacs build via apt
  apt:
    name:
      - clang-format
      - cmake
      - gcc
      - g++
      - libboost-dev
      - python3-dev
      - python3-distutils
  become: yes

