- name: Download Anaconda installer
  get_url:
    url: "{{ anaconda_installer_url }}"
    dest: "{{ anaconda_installer_dir}}"
    mode: 0755

- name: Install Anaconda
  shell:
    cmd: |
      bash {{ anaconda_installer_dir}}/{{ anaconda_installer }} -b -p {{ anaconda_path }}
    creates: "{{ anaconda_path }}"
  become: yes
