# Build and push an image for Qulacs development to GitHub Container Registry.
name: Publish Image

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image-type: clang-format
            dockerfile: Dockerfile.clang-format
          - image-type: conda
            dockerfile: Dockerfile.ubuntu.conda
          - image-type: pyenv
            dockerfile: Dockerfile.ubuntu.pyenv
          - image-type: pyenv-gcc10
            dockerfile: Dockerfile.ubuntu.pyenv.gcc10
    env:
      CONTAINER_REGISTRY: ghcr.io
      # Used for image name, which must be lowercase.
      REPOSITORY_OWNER: qulacs-osaka
      IMAGE_BASE_NAME: qulacs-ubuntu

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_BASE_NAME }}-${{ matrix.image-type }}
          # 'latest' when pushing to main, 'pr-*' when triggered by PR.
          tags: |
            type=raw,enable=${{ github.ref == 'refs/heads/main' }},value=latest
            type=ref,event=pr

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
